"""fix sqlite compatibility bug

Revision ID: 02b7b3b2dfb1
Revises: 348ce2e1f2be
Create Date: 2026-06-19 15:50:28.565169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b7b3b2dfb1'
down_revision: Union[str, None] = '348ce2e1f2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
