"""add branch id to precriptions

Revision ID: 15a1c14d1b9b
Revises: b5d3e2f1a4c6
Create Date: 2026-06-28 13:16:50.814226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision: str = '15a1c14d1b9b'
down_revision: Union[str, None] = 'b5d3e2f1a4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_index('idx_drug_search', postgresql_using='gin')
        batch_op.drop_index('ix_drugs_barcode')
        batch_op.drop_index('ix_drugs_sku')
        batch_op.create_index('uq_drug_org_barcode', ['organization_id', 'barcode'], unique=True)
        batch_op.create_index('uq_drug_org_sku', ['organization_id', 'sku'], unique=True)

    with op.batch_alter_table('insurance_providers', schema=None) as batch_op:
        batch_op.drop_index('ix_insurance_providers_code')
        batch_op.create_index('uq_insurance_org_code', ['organization_id', 'code'], unique=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('onboarding_idempotency_key',
               existing_type=sa.VARCHAR(),
               comment='Stable key used to prevent duplicate organization onboarding',
               existing_nullable=True)
        batch_op.create_index('uq_organizations_onboarding_idempotency_key', ['onboarding_idempotency_key'], unique=True)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.String(36), nullable=True))
        batch_op.drop_index('ix_prescriptions_prescription_number')
        batch_op.create_index('idx_prescription_branch', ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('uq_prescription_org_number', ['organization_id', 'prescription_number'], unique=True)
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_orders_po_number')
        batch_op.create_index('uq_po_branch_number', ['branch_id', 'po_number'], unique=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('idx_role_level')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refunded_by', app.models.db_types.UUID(length=36), nullable=True, comment='User who processed the refund'))
        batch_op.add_column(sa.Column('refund_reason', sa.Text(), nullable=True, comment='Reason for the refund'))
        batch_op.add_column(sa.Column('refund_reference', sa.String(length=100), nullable=True, comment='Unique refund transaction reference'))
        batch_op.drop_index('ix_sales_sale_number')
        batch_op.create_index('uq_sale_branch_number', ['branch_id', 'sale_number'], unique=True)
        batch_op.create_foreign_key(None, 'users', ['refunded_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('uq_sale_branch_number')
        batch_op.create_index('ix_sales_sale_number', ['sale_number'], unique=True)
        batch_op.drop_column('refund_reference')
        batch_op.drop_column('refund_reason')
        batch_op.drop_column('refunded_by')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('idx_role_level', ['level'], unique=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index('uq_po_branch_number')
        batch_op.create_index('ix_purchase_orders_po_number', ['po_number'], unique=True)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('uq_prescription_org_number')
        batch_op.drop_index(batch_op.f('ix_prescriptions_branch_id'))
        batch_op.drop_index('idx_prescription_branch')
        batch_op.create_index('ix_prescriptions_prescription_number', ['prescription_number'], unique=True)
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index('uq_organizations_onboarding_idempotency_key')
        batch_op.alter_column('onboarding_idempotency_key',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Stable key used to prevent duplicate organization onboarding',
               existing_nullable=True)

    with op.batch_alter_table('insurance_providers', schema=None) as batch_op:
        batch_op.drop_index('uq_insurance_org_code')
        batch_op.create_index('ix_insurance_providers_code', ['code'], unique=True)

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_index('uq_drug_org_sku')
        batch_op.drop_index('uq_drug_org_barcode')
        batch_op.create_index('ix_drugs_sku', ['sku'], unique=True)
        batch_op.create_index('ix_drugs_barcode', ['barcode'], unique=True)
        batch_op.create_index('idx_drug_search', ['search_vector'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
