"""add branch id to precriptions

Revision ID: 15a1c14d1b9b
Revises: b5d3e2f1a4c6
Create Date: 2026-06-28 13:16:50.814226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision: str = '15a1c14d1b9b'
down_revision: Union[str, None] = 'b5d3e2f1a4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(bind: sa.Connection, table: str) -> set[str]:
    return {column["name"] for column in sa.inspect(bind).get_columns(table)}


def _indexes(bind: sa.Connection, table: str) -> set[str]:
    return {
        index["name"] for index in sa.inspect(bind).get_indexes(table)
        if index.get("name")
    }


def _foreign_keys(bind: sa.Connection, table: str) -> list[dict]:
    return sa.inspect(bind).get_foreign_keys(table)


def upgrade() -> None:
    # Rewritten as introspection-based/idempotent — see fa1b2c3d4e5f
    # (reconcile_production_schema) and 1a2b3c4d5e6f (repair_role_level_schema_drift)
    # for the same defensive pattern already established in this chain.
    #
    # The original autogenerated diff assumed a linear history, but this
    # migration's branch (off b5d3e2f1a4c6) runs in parallel with — and
    # merges after — the branch containing 7e8f9a0b1c2d
    # (scope_business_identifiers_by_tenant) and fa1b2c3d4e5f
    # (reconcile_production_schema), both of which already apply the
    # prescriptions.branch_id column/FK/indexes, the sales refund columns,
    # and the drugs/insurance_providers/purchase_orders index-scoping this
    # migration also attempted. On a genuinely fresh database those
    # unconditional operations collide with what already ran ("column
    # already exists", "index does not exist") — `alembic upgrade head`
    # failed outright on any new install. It additionally dropped
    # idx_drug_search (the drugs GIN full-text index) with nothing in the
    # chain ever recreating it — an unintended search-performance
    # regression on every install. See
    # docs/reviews/2026-08-05-live-deployment-orchestration-report.md.
    #
    # This version only performs each operation if the target state isn't
    # already there, so it's correct regardless of which parallel branch
    # Alembic happens to apply first.
    bind = op.get_bind()

    prescriptions_columns = _columns(bind, "prescriptions")
    if "branch_id" not in prescriptions_columns:
        with op.batch_alter_table('prescriptions', schema=None) as batch_op:
            batch_op.add_column(sa.Column('branch_id', sa.String(36), nullable=True))

    prescriptions_indexes = _indexes(bind, "prescriptions")
    if "idx_prescription_branch" not in prescriptions_indexes:
        op.create_index('idx_prescription_branch', 'prescriptions', ['branch_id'], unique=False)
    if "ix_prescriptions_branch_id" not in prescriptions_indexes:
        op.create_index('ix_prescriptions_branch_id', 'prescriptions', ['branch_id'], unique=False)

    has_prescriptions_branch_fk = any(
        fk.get("constrained_columns") == ["branch_id"] and fk.get("referred_table") == "branches"
        for fk in _foreign_keys(bind, "prescriptions")
    )
    if not has_prescriptions_branch_fk:
        with op.batch_alter_table('prescriptions', schema=None) as batch_op:
            batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')

    if "idx_role_level" in _indexes(bind, "roles"):
        with op.batch_alter_table('roles', schema=None) as batch_op:
            batch_op.drop_index('idx_role_level')

    sales_columns = _columns(bind, "sales")
    with op.batch_alter_table('sales', schema=None) as batch_op:
        if "refunded_by" not in sales_columns:
            batch_op.add_column(sa.Column('refunded_by', app.models.db_types.UUID(length=36), nullable=True, comment='User who processed the refund'))
        if "refund_reason" not in sales_columns:
            batch_op.add_column(sa.Column('refund_reason', sa.Text(), nullable=True, comment='Reason for the refund'))
        if "refund_reference" not in sales_columns:
            batch_op.add_column(sa.Column('refund_reference', sa.String(length=100), nullable=True, comment='Unique refund transaction reference'))

    has_sales_refunded_by_fk = any(
        fk.get("constrained_columns") == ["refunded_by"] and fk.get("referred_table") == "users"
        for fk in _foreign_keys(bind, "sales")
    )
    if not has_sales_refunded_by_fk:
        with op.batch_alter_table('sales', schema=None) as batch_op:
            batch_op.create_foreign_key(None, 'users', ['refunded_by'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    # These objects are owned by this migration or earlier ones depending on
    # which parallel branch created them first (see upgrade()) — a repair-
    # style downgrade cannot safely know which, so this is a no-op rather
    # than risking dropping columns/constraints another migration still
    # depends on. Matches fa1b2c3d4e5f's downgrade() for the same reason.
    pass
