"""add audit logging

Revision ID: 348ce2e1f2be
Revises: b4a2c6d8e9f1
Create Date: 2026-06-19 13:10:28.549030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348ce2e1f2be'
down_revision: Union[str, None] = 'b4a2c6d8e9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch_inventory', schema=None) as batch_op:
        batch_op.alter_column('selling_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Branch-specific selling price override',
               existing_nullable=True)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique branch code within an organization for transactions',
               existing_comment='Unique branch code for transactions',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique branch code for transactions',
               existing_comment='Unique branch code within an organization for transactions',
               existing_nullable=False)

    with op.batch_alter_table('branch_inventory', schema=None) as batch_op:
        batch_op.alter_column('selling_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Branch-specific selling price override',
               existing_nullable=True)

    # ### end Alembic commands ###
