"""add_is_super_admin_to_users

Revision ID: 5c824f626a8e
Revises: 7c05258c4b0e
Create Date: 2026-06-23 17:31:38.530188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c824f626a8e'
down_revision: Union[str, None] = '7c05258c4b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
