"""add salecontract fields

Revision ID: a91cfcc34459
Revises: e9f1a2b3c4d5
Create Date: 2026-06-26 18:30:25.699134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91cfcc34459'
down_revision: Union[str, None] = 'e9f1a2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_approval', sa.Boolean(), nullable=False, server_default='false', comment='Require manager approval before applying during checkout'))
        batch_op.add_column(sa.Column('daily_usage_limit', sa.Integer(), nullable=True, comment='Maximum number of completed sales that may use this contract per day'))
        batch_op.add_column(sa.Column('per_customer_usage_limit', sa.Integer(), nullable=True, comment='Maximum completed sales a single customer may process with this contract'))
        batch_op.add_column(sa.Column('requires_preauthorization', sa.Boolean(), nullable=False, server_default='false', comment='Require a pre-authorization number before applying this contract'))

    with op.batch_alter_table('sale_item_batch_allocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refunded_quantity', sa.Integer(), nullable=False, server_default='0', comment='Cumulative units refunded from this batch allocation'))

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refunded_quantity', sa.Integer(), nullable=False, server_default='0', comment='Cumulative units refunded from this sale line'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_column('refunded_quantity')

    with op.batch_alter_table('sale_item_batch_allocations', schema=None) as batch_op:
        batch_op.drop_column('refunded_quantity')

    with op.batch_alter_table('price_contracts', schema=None) as batch_op:
        batch_op.drop_column('requires_preauthorization')
        batch_op.drop_column('per_customer_usage_limit')
        batch_op.drop_column('daily_usage_limit')
        batch_op.drop_column('requires_approval')

    # ### end Alembic commands ###
