/**
 * eventEnvelope.ts
 * ================
 * TypeScript mirror of backend.laso/app/schemas/event_envelope.py.
 *
 * MUST stay byte-identical to the Python side for hash_self computation.
 * Validated against envelope-golden-vectors.json (generated by
 * tests/unit/test_event_envelope_golden_vectors.py — run it to regenerate).
 *
 * ADRs 0006, 0007, 0008.
 */

export const GENESIS_HASH = "0".repeat(64);
export const ULID_LENGTH = 26;
export const SHA256_HEX_LENGTH = 64;
export const MAX_PUSH_BATCH = 500;

// ── Enums ──────────────────────────────────────────────────────────────────

export type AggregateType =
  | "sale"
  | "prescription"
  | "customer"
  | "stock"
  | "stock_transfer"
  | "drug"
  | "drug_category"
  | "drug_batch"
  | "branch_inventory"
  | "purchase_order";

export type EventStatus =
  | "accepted"
  | "accepted_deferred"
  | "rejected_permanent"
  | "rejected_transient";

// ── Envelope ───────────────────────────────────────────────────────────────

export interface EventEnvelope {
  event_id: string;            // 26-char ULID
  aggregate_id: string;        // UUID
  aggregate_type: AggregateType;
  event_type: string;
  schema_version: number;
  payload: Record<string, unknown>;
  dependencies: string[];      // ULIDs of events this one depends on
  authored_at: string;         // ISO 8601 UTC "YYYY-MM-DDTHH:mm:ss.SSSZ"
  authored_by: string;         // UUID
  branch_id: string;           // UUID
  org_id: string;              // UUID
  hash_self: string;           // 64-char hex SHA-256
  hash_prev?: string | null;
  seq?: number | null;
  received_at?: string | null;
}

// ── Push / Pull wire types (ADR 0008) ─────────────────────────────────────

export interface EventPushRequest {
  branch_id: string;
  client_clock: string;        // ISO 8601
  events: EventEnvelope[];
}

export interface EventPushResult {
  event_id: string;
  status: EventStatus;
  seq?: number | null;
  received_at?: string | null;
  error_code?: string | null;
  error_message?: string | null;
  pending_on?: string[] | null;
}

export interface EventPushResponse {
  server_clock: string;
  results: EventPushResult[];
  next_pull_seq: number;
}

export interface EventPullResponse {
  server_clock: string;
  events: EventEnvelope[];
  has_more: boolean;
  next_after_seq: number;
}

// ── ULID generation ────────────────────────────────────────────────────────
//
// 10 timestamp chars (48-bit ms since epoch) + 16 random chars (80 bits).
// Crockford base32 alphabet — lex-sortable within the same millisecond.

const CROCKFORD_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

export function generateUlid(): string {
  // Timestamp part — 10 chars from 48-bit ms
  const ts = Date.now();
  let t = ts;
  let timePart = "";
  for (let i = 9; i >= 0; i--) {
    timePart = CROCKFORD_ALPHABET[t % 32] + timePart;
    t = Math.floor(t / 32);
  }

  // Random part — 16 chars from 80 random bits
  const rand = new Uint8Array(10);
  crypto.getRandomValues(rand);
  let randBits = 0n;
  for (const b of rand) randBits = (randBits << 8n) | BigInt(b);

  let randPart = "";
  for (let i = 15; i >= 0; i--) {
    randPart = CROCKFORD_ALPHABET[Number(randBits & 31n)] + randPart;
    randBits >>= 5n;
  }

  return timePart + randPart;
}

// ── Canonical JSON (ADR 0007) ──────────────────────────────────────────────
//
// MUST be byte-identical to Python's:
//   json.dumps(obj, separators=(",",":"), sort_keys=True, ensure_ascii=False)
// with custom serializers:
//   datetime → toISOString()    (same "YYYY-MM-DDTHH:mm:ss.SSSZ" format)
//   UUID     → lower-case hex-with-hyphens  (already a string here)
//   Enum     → string value                 (already a string here)
//
// The sort_keys=True applies recursively to nested objects. Arrays are
// NOT sorted — their element order is preserved.

function _canonicalValue(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") {
    if (!Number.isFinite(v)) {
      throw new Error(`canonical_json: non-finite number ${v}`);
    }
    return JSON.stringify(v);
  }
  if (typeof v === "string") return JSON.stringify(v);
  if (v instanceof Date) return JSON.stringify(v.toISOString());
  if (Array.isArray(v)) {
    return "[" + v.map(_canonicalValue).join(",") + "]";
  }
  if (typeof v === "object") {
    const obj = v as Record<string, unknown>;
    const keys = Object.keys(obj).sort();
    const pairs = keys.map((k) => JSON.stringify(k) + ":" + _canonicalValue(obj[k]));
    return "{" + pairs.join(",") + "}";
  }
  throw new Error(`canonical_json: cannot serialize ${typeof v}`);
}

export function canonicalJson(obj: Record<string, unknown>): string {
  return _canonicalValue(obj);
}

// ── hash_self computation (ADR 0007) ────────────────────────────────────────
//
// SHA-256 of the canonical JSON of the envelope body with hash_prev substituted.
// Fields hashed (in sort order — canonical_json sorts keys):
//   aggregate_id, aggregate_type, authored_at, authored_by, branch_id,
//   dependencies, event_id, event_type, hash_prev, org_id, payload,
//   schema_version
//
// hash_prev is passed explicitly because the client writes with a local
// placeholder and the server re-verifies with the real chain tail.

const _HASH_FIELDS: (keyof Omit<EventEnvelope, "hash_self" | "seq" | "received_at">)[] = [
  "event_id",
  "aggregate_id",
  "aggregate_type",
  "event_type",
  "schema_version",
  "payload",
  "dependencies",
  "authored_at",
  "authored_by",
  "branch_id",
  "org_id",
];

export async function computeHashSelf(
  envelope: Omit<EventEnvelope, "hash_self">,
  hashPrev: string,
): Promise<string> {
  const body: Record<string, unknown> = {};
  for (const field of _HASH_FIELDS) {
    body[field] = envelope[field];
  }
  body["hash_prev"] = hashPrev;

  const json = canonicalJson(body);
  const bytes = new TextEncoder().encode(json);
  const buf = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}
