"""Canonical demo pharmacy catalog.

The entries are intentionally synthetic. Prices are test values in Ghana cedis,
barcodes are omitted to avoid presenting invented identifiers as real GS1 data,
and every SKU is namespaced with ``DEMO-`` so seed-owned rows are unambiguous.
"""

from dataclasses import dataclass
from decimal import Decimal


@dataclass(frozen=True, slots=True)
class CategorySeed:
    key: str
    name: str
    description: str


@dataclass(frozen=True, slots=True)
class DrugSeed:
    sku: str
    name: str
    generic_name: str
    category_key: str
    drug_type: str
    dosage_form: str
    strength: str
    unit_price: Decimal
    cost_price: Decimal
    requires_prescription: bool = False
    controlled_substance_schedule: str | None = None
    unit_of_measure: str = "unit"
    opening_quantity: int = 100
    reorder_level: int = 20
    reorder_quantity: int = 50
    location: str = "Demo Shelf"


CATEGORIES: tuple[CategorySeed, ...] = (
    CategorySeed("pain", "Pain & Fever", "Analgesic and antipyretic demo products."),
    CategorySeed(
        "anti_infective",
        "Anti-infectives",
        "Antibiotic and antimalarial demo products.",
    ),
    CategorySeed(
        "cardiovascular",
        "Cardiovascular",
        "Blood pressure and lipid management demo products.",
    ),
    CategorySeed(
        "metabolic",
        "Diabetes & Metabolic",
        "Diabetes and metabolic health demo products.",
    ),
    CategorySeed(
        "gastrointestinal", "Gastrointestinal", "Digestive health demo products."
    ),
    CategorySeed(
        "respiratory", "Respiratory & Allergy", "Respiratory and allergy demo products."
    ),
    CategorySeed(
        "supplements",
        "Vitamins & Supplements",
        "Vitamin, mineral, and herbal demo products.",
    ),
    CategorySeed("dermatology", "Dermatology", "Topical skin-care demo products."),
    CategorySeed("eye_ear", "Eye & Ear Care", "Ophthalmic and otic demo products."),
    CategorySeed("first_aid", "First Aid", "Antiseptic and first-aid demo products."),
)


def _d(value: str) -> Decimal:
    return Decimal(value)


CATALOG: tuple[DrugSeed, ...] = (
    DrugSeed(
        "DEMO-PARA-500-TAB",
        "Paracetamol 500 mg Tablets",
        "Paracetamol",
        "pain",
        "otc",
        "tablet",
        "500 mg",
        _d("8.00"),
        _d("4.50"),
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-PARA-120-SYR",
        "Paracetamol Oral Suspension",
        "Paracetamol",
        "pain",
        "otc",
        "suspension",
        "120 mg/5 mL",
        _d("18.00"),
        _d("11.00"),
        unit_of_measure="bottle",
        opening_quantity=60,
    ),
    DrugSeed(
        "DEMO-IBU-400-TAB",
        "Ibuprofen 400 mg Tablets",
        "Ibuprofen",
        "pain",
        "otc",
        "tablet",
        "400 mg",
        _d("14.00"),
        _d("8.00"),
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-DIC-50-TAB",
        "Diclofenac 50 mg Tablets",
        "Diclofenac sodium",
        "pain",
        "prescription",
        "tablet",
        "50 mg",
        _d("16.00"),
        _d("9.00"),
        True,
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-ASA-75-TAB",
        "Aspirin 75 mg Tablets",
        "Acetylsalicylic acid",
        "cardiovascular",
        "prescription",
        "tablet",
        "75 mg",
        _d("12.00"),
        _d("7.00"),
        True,
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-TRAM-50-CAP",
        "Tramadol 50 mg Capsules",
        "Tramadol hydrochloride",
        "pain",
        "controlled",
        "capsule",
        "50 mg",
        _d("24.00"),
        _d("15.00"),
        True,
        "IV",
        "box",
        40,
        10,
        20,
        "Controlled Demo Shelf",
    ),
    DrugSeed(
        "DEMO-AMOX-500-CAP",
        "Amoxicillin 500 mg Capsules",
        "Amoxicillin",
        "anti_infective",
        "prescription",
        "capsule",
        "500 mg",
        _d("28.00"),
        _d("18.00"),
        True,
        unit_of_measure="box",
        opening_quantity=80,
    ),
    DrugSeed(
        "DEMO-AZITH-500-TAB",
        "Azithromycin 500 mg Tablets",
        "Azithromycin",
        "anti_infective",
        "prescription",
        "tablet",
        "500 mg",
        _d("42.00"),
        _d("28.00"),
        True,
        unit_of_measure="box",
        opening_quantity=50,
    ),
    DrugSeed(
        "DEMO-CIPRO-500-TAB",
        "Ciprofloxacin 500 mg Tablets",
        "Ciprofloxacin",
        "anti_infective",
        "prescription",
        "tablet",
        "500 mg",
        _d("32.00"),
        _d("21.00"),
        True,
        unit_of_measure="box",
        opening_quantity=60,
    ),
    DrugSeed(
        "DEMO-METRO-400-TAB",
        "Metronidazole 400 mg Tablets",
        "Metronidazole",
        "anti_infective",
        "prescription",
        "tablet",
        "400 mg",
        _d("20.00"),
        _d("12.00"),
        True,
        unit_of_measure="box",
        opening_quantity=90,
    ),
    DrugSeed(
        "DEMO-COTRIM-960-TAB",
        "Co-trimoxazole 960 mg Tablets",
        "Sulfamethoxazole/Trimethoprim",
        "anti_infective",
        "prescription",
        "tablet",
        "960 mg",
        _d("26.00"),
        _d("16.00"),
        True,
        unit_of_measure="box",
        opening_quantity=60,
    ),
    DrugSeed(
        "DEMO-CEFURO-500-TAB",
        "Cefuroxime 500 mg Tablets",
        "Cefuroxime axetil",
        "anti_infective",
        "prescription",
        "tablet",
        "500 mg",
        _d("55.00"),
        _d("38.00"),
        True,
        unit_of_measure="box",
        opening_quantity=40,
    ),
    DrugSeed(
        "DEMO-AL-20-120-TAB",
        "Artemether/Lumefantrine Tablets",
        "Artemether/Lumefantrine",
        "anti_infective",
        "prescription",
        "tablet",
        "20 mg/120 mg",
        _d("36.00"),
        _d("24.00"),
        True,
        unit_of_measure="pack",
        opening_quantity=70,
    ),
    DrugSeed(
        "DEMO-AMLO-5-TAB",
        "Amlodipine 5 mg Tablets",
        "Amlodipine",
        "cardiovascular",
        "prescription",
        "tablet",
        "5 mg",
        _d("18.00"),
        _d("10.00"),
        True,
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-LOSAR-50-TAB",
        "Losartan 50 mg Tablets",
        "Losartan potassium",
        "cardiovascular",
        "prescription",
        "tablet",
        "50 mg",
        _d("24.00"),
        _d("14.00"),
        True,
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-LISIN-10-TAB",
        "Lisinopril 10 mg Tablets",
        "Lisinopril",
        "cardiovascular",
        "prescription",
        "tablet",
        "10 mg",
        _d("20.00"),
        _d("12.00"),
        True,
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-ATOR-20-TAB",
        "Atorvastatin 20 mg Tablets",
        "Atorvastatin",
        "cardiovascular",
        "prescription",
        "tablet",
        "20 mg",
        _d("30.00"),
        _d("19.00"),
        True,
        unit_of_measure="box",
        opening_quantity=70,
    ),
    DrugSeed(
        "DEMO-FURO-40-TAB",
        "Furosemide 40 mg Tablets",
        "Furosemide",
        "cardiovascular",
        "prescription",
        "tablet",
        "40 mg",
        _d("15.00"),
        _d("8.50"),
        True,
        unit_of_measure="box",
        opening_quantity=70,
    ),
    DrugSeed(
        "DEMO-METF-500-TAB",
        "Metformin 500 mg Tablets",
        "Metformin hydrochloride",
        "metabolic",
        "prescription",
        "tablet",
        "500 mg",
        _d("18.00"),
        _d("10.00"),
        True,
        unit_of_measure="box",
        opening_quantity=120,
    ),
    DrugSeed(
        "DEMO-GLIB-5-TAB",
        "Glibenclamide 5 mg Tablets",
        "Glibenclamide",
        "metabolic",
        "prescription",
        "tablet",
        "5 mg",
        _d("16.00"),
        _d("9.00"),
        True,
        unit_of_measure="box",
        opening_quantity=80,
    ),
    DrugSeed(
        "DEMO-OMEP-20-CAP",
        "Omeprazole 20 mg Capsules",
        "Omeprazole",
        "gastrointestinal",
        "otc",
        "capsule",
        "20 mg",
        _d("18.00"),
        _d("10.00"),
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-ORS-SACHET",
        "Oral Rehydration Salts",
        "Oral rehydration salts",
        "gastrointestinal",
        "otc",
        "powder",
        "WHO formula",
        _d("3.50"),
        _d("1.80"),
        unit_of_measure="sachet",
        opening_quantity=200,
        reorder_level=40,
        reorder_quantity=100,
    ),
    DrugSeed(
        "DEMO-ANTACID-200-SUS",
        "Antacid Oral Suspension",
        "Aluminium hydroxide/Magnesium hydroxide",
        "gastrointestinal",
        "otc",
        "suspension",
        "200 mL",
        _d("22.00"),
        _d("14.00"),
        unit_of_measure="bottle",
        opening_quantity=60,
    ),
    DrugSeed(
        "DEMO-LOPER-2-CAP",
        "Loperamide 2 mg Capsules",
        "Loperamide",
        "gastrointestinal",
        "otc",
        "capsule",
        "2 mg",
        _d("12.00"),
        _d("7.00"),
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-BISA-5-TAB",
        "Bisacodyl 5 mg Tablets",
        "Bisacodyl",
        "gastrointestinal",
        "otc",
        "tablet",
        "5 mg",
        _d("11.00"),
        _d("6.00"),
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-CET-10-TAB",
        "Cetirizine 10 mg Tablets",
        "Cetirizine",
        "respiratory",
        "otc",
        "tablet",
        "10 mg",
        _d("12.00"),
        _d("7.00"),
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-LORA-10-TAB",
        "Loratadine 10 mg Tablets",
        "Loratadine",
        "respiratory",
        "otc",
        "tablet",
        "10 mg",
        _d("15.00"),
        _d("9.00"),
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-CPM-4-TAB",
        "Chlorpheniramine 4 mg Tablets",
        "Chlorpheniramine maleate",
        "respiratory",
        "otc",
        "tablet",
        "4 mg",
        _d("9.00"),
        _d("5.00"),
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-SALB-100-INH",
        "Salbutamol Inhaler",
        "Salbutamol",
        "respiratory",
        "prescription",
        "inhaler",
        "100 mcg/dose",
        _d("48.00"),
        _d("34.00"),
        True,
        unit_of_measure="inhaler",
        opening_quantity=30,
        reorder_level=8,
        reorder_quantity=20,
    ),
    DrugSeed(
        "DEMO-DEXTRO-SYR",
        "Dextromethorphan Cough Syrup",
        "Dextromethorphan",
        "respiratory",
        "otc",
        "syrup",
        "15 mg/5 mL",
        _d("24.00"),
        _d("15.00"),
        unit_of_measure="bottle",
        opening_quantity=50,
    ),
    DrugSeed(
        "DEMO-VITC-1000-TAB",
        "Vitamin C 1000 mg Tablets",
        "Ascorbic acid",
        "supplements",
        "supplement",
        "tablet",
        "1000 mg",
        _d("22.00"),
        _d("14.00"),
        unit_of_measure="bottle",
        opening_quantity=60,
    ),
    DrugSeed(
        "DEMO-FOLIC-5-TAB",
        "Folic Acid 5 mg Tablets",
        "Folic acid",
        "supplements",
        "supplement",
        "tablet",
        "5 mg",
        _d("10.00"),
        _d("5.50"),
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-FERROUS-200-TAB",
        "Ferrous Sulfate 200 mg Tablets",
        "Ferrous sulfate",
        "supplements",
        "supplement",
        "tablet",
        "200 mg",
        _d("16.00"),
        _d("9.00"),
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-MULTI-TAB",
        "Daily Multivitamin Tablets",
        "Multivitamins and minerals",
        "supplements",
        "supplement",
        "tablet",
        "standard",
        _d("28.00"),
        _d("18.00"),
        unit_of_measure="bottle",
        opening_quantity=50,
    ),
    DrugSeed(
        "DEMO-ZINC-20-TAB",
        "Zinc 20 mg Tablets",
        "Zinc sulfate",
        "supplements",
        "supplement",
        "tablet",
        "20 mg",
        _d("14.00"),
        _d("8.00"),
        unit_of_measure="box",
    ),
    DrugSeed(
        "DEMO-MORINGA-500-CAP",
        "Moringa Leaf 500 mg Capsules",
        "Moringa oleifera leaf",
        "supplements",
        "herbal",
        "capsule",
        "500 mg",
        _d("30.00"),
        _d("19.00"),
        unit_of_measure="bottle",
        opening_quantity=40,
    ),
    DrugSeed(
        "DEMO-CLOTRI-1-CRM",
        "Clotrimazole 1% Cream",
        "Clotrimazole",
        "dermatology",
        "otc",
        "cream",
        "1% w/w",
        _d("20.00"),
        _d("12.00"),
        unit_of_measure="tube",
        opening_quantity=50,
    ),
    DrugSeed(
        "DEMO-HYDRO-1-CRM",
        "Hydrocortisone 1% Cream",
        "Hydrocortisone",
        "dermatology",
        "otc",
        "cream",
        "1% w/w",
        _d("18.00"),
        _d("11.00"),
        unit_of_measure="tube",
        opening_quantity=50,
    ),
    DrugSeed(
        "DEMO-CHLOR-EYE",
        "Chloramphenicol Eye Drops",
        "Chloramphenicol",
        "eye_ear",
        "prescription",
        "eye drops",
        "0.5% w/v",
        _d("24.00"),
        _d("15.00"),
        True,
        unit_of_measure="bottle",
        opening_quantity=35,
    ),
    DrugSeed(
        "DEMO-LUBE-EYE",
        "Lubricating Eye Drops",
        "Hypromellose",
        "eye_ear",
        "otc",
        "eye drops",
        "0.3% w/v",
        _d("26.00"),
        _d("17.00"),
        unit_of_measure="bottle",
        opening_quantity=35,
    ),
    DrugSeed(
        "DEMO-POVIDONE-10",
        "Povidone-Iodine Antiseptic",
        "Povidone-iodine",
        "first_aid",
        "otc",
        "solution",
        "10% w/v",
        _d("20.00"),
        _d("12.00"),
        unit_of_measure="bottle",
        opening_quantity=50,
    ),
    DrugSeed(
        "DEMO-IPA-70",
        "Isopropyl Alcohol",
        "Isopropyl alcohol",
        "first_aid",
        "otc",
        "solution",
        "70% v/v",
        _d("16.00"),
        _d("9.00"),
        unit_of_measure="bottle",
        opening_quantity=70,
    ),
)
